### ISSUE TITLE
Known Issues

### ISSUE THREAD

**Issue by maxwellbenton** [learn-co-curriculum/activerecord-associations-intro#24]
Problem: Associated video does not line up with readme #23 

Solution: Update or remove video

**Comment by Sdcrouse** [comment]
Hi. I ran the code from Avi's video from the section mentioned in the issue. Strangely enough, it works! The SQL didn't show up as in the video, but that may be because he was using rails console, while I was using rake console.

Here's the key difference: this lesson (the codealong, not the video) has you set someone_like_you.artist = adele, then IMMEDIATELY check adele.songs, which returns []. However, in Avi's video, he set runaway.artist = kanye, then SAVED runaway. When I did this, running kanye.songs after that showed that runaway was indeed in kanye's songs array.

It seems that saving the song will automatically put the song into the artist's songs array.

**Comment by maxwellbenton** [comment]
Thank you @Sdcrouse for this information!

We've updated this lessons content, and based on your feedback, have updated it to include the use of `save`, which also helps to align the lesson with this video, resolving this issue.

Thanks again!
